### ISSUE TITLE
`encodingindex.dtd` not found when file path to `encodingindex.xml` contains spaces

### ISSUE THREAD

**Issue by heiwiper** [aymanosman/arm-spec#1]
I was facing this issue the other day when I tried to run the code for the first time when I changed the variable `*encoding-index-path*` to read the file in the repo folder. The parser would crash when it looks for `encodingindex.dtd` for some reason. Here's the following error message:
```
The file
#P"/home/heiwiper/Projects/arm%20spec/encodingindex.dtd"
does not exist:
  No such file or directory
```

**Comment by heiwiper** [comment]
I added instructions to copy the files to `~/.cache/`
Here's the commit let me know if I should make a PR or if there's better way to fix it.
https://github.com/heiwiper/arm-spec/commit/e833c2774fec5451e161b44fd8ecd5f3f5f71206

**Comment by aymanosman** [comment]
Or, even better, just reference the files in the repo instead. I obviously just forgot to change the paths.

**Comment by aymanosman** [comment]
I've pushed a commit fixing this.

**Comment by heiwiper** [comment]
Yes that makes more sense but there would still be an error if the path to the xml file contains a space ?

**Comment by aymanosman** [comment]
Don’t think so. How are you running the script?

**Comment by heiwiper** [comment]
I'm using the REPL (SLY), but running the command in the README file leads to the same error.

**Comment by aymanosman** [comment]
OK, I would just move the repo to the directory `arm-spec` instead of `arm spec` as I think this is a bug in the underlying xml library. When it seems to url-encode the path it constructs for the dtd file.
